### ISSUE TITLE
Page loads with a white border around viewport, then disappears 

### ISSUE THREAD

**Issue by tomgco** [yldio/website#106]
![yld io](https://user-images.githubusercontent.com/524382/41784745-8e0a02cc-7638-11e8-8b37-7792b1808928.gif)

## Browser Information

http://whatsmybrowser.org/b/GKP5NTM

## Reason

Gives a yanky / jarring first impression to yld.io

**Comment by jsheldrake** [comment]
Fixed this issue in PR #109 https://github.com/yldio/website/pull/109
