### ISSUE TITLE
Mobile header colouring is not like on design

### ISSUE THREAD

**Issue by AniaMakes** [yldio/website#71]
It's pink, and you can see that the image on the background has been cropped, but on the design it is shrunk rather than cropped. 

**Design**
![design](https://user-images.githubusercontent.com/31079643/41532548-615cafe6-72ef-11e8-9207-dc757e9965fe.png)

**Our website**
![menu](https://user-images.githubusercontent.com/31079643/41532561-6a072914-72ef-11e8-97e0-ceceb37af066.png)

**Comment by ramitos** [comment]
I think that is because of the position of the bg image
