### ISSUE TITLE
About us: video needs repositioning?

### ISSUE THREAD

**Issue by AniaMakes** [yldio/website#72]
On design, the video is a separate "row" and doesn't overlap any elements

![about-us-video](https://user-images.githubusercontent.com/31079643/41532686-e6b8f280-72ef-11e8-8bf6-73cd3f55402f.png)

**Comment by ramitos** [comment]
it needs 15 as the top margin in xs, instead of a negative margin. example: https://github.com/yldio/website/blob/ff78317a11f0cf1870f802cb8a76e9a24abd6917/src/sections/what-we-do.js#L68
