### ISSUE TITLE
Services: enabling - card out of line - deliberate or not?

### ISSUE THREAD

**Issue by AniaMakes** [yldio/website#73]
The Enabling card is a little bit bigger than the rest - it has more content, but this minimal difference looks odd. 

![screenshot from 2018-06-18 12-09-44](https://user-images.githubusercontent.com/31079643/41532865-98c85d80-72f0-11e8-90ed-724e4578d051.png)

**Comment by SaraVieira** [comment]
Any idea how to fix this without setting a px height ?

**Comment by AniaMakes** [comment]
In React, is there a way for sibling components to share information about each other? So they can look at each other, check who is the highest, and all adapt that height?

**Comment by ramitos** [comment]
@AniaMakes yes, with the context api. It’s a good idea 😉
